export const LANGUAGE_OPTIONS_ARRAY = [
  { countryValue: 'aae', name: 'Arbërisht' },
  { countryValue: 'ab', name: 'аҧсшәа' },
  { countryValue: 'abr', name: 'Abron' },
  { countryValue: 'abs', name: 'bahasa ambon' },
  { countryValue: 'ace', name: 'Acèh' },
  { countryValue: 'acf', name: 'Kwéyòl Sent Lisi' },
  { countryValue: 'acm', name: 'عراقي' },
  { countryValue: 'ady', name: 'адыгабзэ' },
  { countryValue: 'ady-cyrl', name: 'адыгабзэ' },
  { countryValue: 'aeb', name: 'تونسي / Tûnsî' },
  { countryValue: 'aeb-arab', name: 'تونسي' },
  { countryValue: 'aeb-latn', name: 'Tûnsî' },
  { countryValue: 'af', name: 'Afrikaans' },
  { countryValue: 'aig', name: "Aanteegan an' Baabyuudan" },
  { countryValue: 'aln', name: 'Gegë' },
  { countryValue: 'alt', name: 'алтай тил' },
  { countryValue: 'am', name: 'አማርኛ' },
  { countryValue: 'ami', name: 'Pangcah' },
  { countryValue: 'an', name: 'aragonés' },
  { countryValue: 'ang', name: 'Ænglisc' },
  { countryValue: 'ann', name: 'Obolo' },
  { countryValue: 'anp', name: 'अंगिका' },
  { countryValue: 'apc', name: 'شامي' },
  { countryValue: 'ar', name: 'العربية' },
  { countryValue: 'arc', name: 'ܐܪܡܝܐ' },
  { countryValue: 'arn', name: 'mapudungun' },
  { countryValue: 'arq', name: 'جازايرية' },
  { countryValue: 'ary', name: 'الدارجة' },
  { countryValue: 'arz', name: 'مصرى' },
  { countryValue: 'as', name: 'অসমীয়া' },
  { countryValue: 'ase', name: 'American sign language' },
  { countryValue: 'ast', name: 'asturianu' },
  { countryValue: 'atj', name: 'Atikamekw' },
  { countryValue: 'av', name: 'авар' },
  { countryValue: 'avk', name: 'Kotava' },
  { countryValue: 'awa', name: 'अवधी' },
  { countryValue: 'ay', name: 'Aymar aru' },
  { countryValue: 'az', name: 'azərbaycanca' },
  { countryValue: 'azb', name: 'تۆرکجه' },
  { countryValue: 'ba', name: 'башҡортса' },
  { countryValue: 'ban', name: 'Basa Bali' },
  { countryValue: 'ban-bali', name: 'ᬩᬲᬩᬮᬶ' },
  { countryValue: 'bar', name: 'Boarisch' },
  { countryValue: 'bbc', name: 'Batak Toba' },
  { countryValue: 'bbc-latn', name: 'Batak Toba' },
  { countryValue: 'bcc', name: 'جهلسری بلوچی' },
  { countryValue: 'bci', name: 'wawle' },
  { countryValue: 'bcl', name: 'Bikol Central' },
  { countryValue: 'bdr', name: 'Bajau Sama' },
  { countryValue: 'be', name: 'беларуская' },
  { countryValue: 'be-tarask', name: 'беларуская (тарашкевіца)' },
  { countryValue: 'bew', name: 'Betawi' },
  { countryValue: 'bg', name: 'български' },
  { countryValue: 'bgc', name: 'हरियाणवी' },
  { countryValue: 'bgn', name: 'روچ کپتین بلوچی' },
  { countryValue: 'bh', name: 'भोजपुरी' },
  { countryValue: 'bho', name: 'भोजपुरी' },
  { countryValue: 'bi', name: 'Bislama' },
  { countryValue: 'bjn', name: 'Banjar' },
  { countryValue: 'blk', name: 'ပအိုဝ်ႏဘာႏသာႏ' },
  { countryValue: 'bm', name: 'bamanankan' },
  { countryValue: 'bn', name: 'বাংলা' },
  { countryValue: 'bo', name: 'བོད་ཡིག' },
  { countryValue: 'bol', name: 'bòo pìkkà' },
  { countryValue: 'bpy', name: 'বিষ্ণুপ্রিয়া মণিপুরী' },
  { countryValue: 'bqi', name: 'بختیاری' },
  { countryValue: 'br', name: 'brezhoneg' },
  { countryValue: 'brh', name: 'Bráhuí' },
  { countryValue: 'bs', name: 'bosanski' },
  { countryValue: 'btm', name: 'Batak Mandailing' },
  { countryValue: 'bto', name: 'Iriga Bicolano' },
  { countryValue: 'bug', name: 'Basa Ugi' },
  { countryValue: 'bug-bugi', name: 'ᨅᨔ ᨕᨘᨁᨗ' },
  { countryValue: 'bxr', name: 'буряад' },
  { countryValue: 'ca', name: 'català' },
  { countryValue: 'cbk-zam', name: 'Chavacano de Zamboanga' },
  { countryValue: 'ccp', name: '𑄌𑄋𑄴𑄟𑄳𑄦' },
  { countryValue: 'cdo', name: '閩東語 / Mìng-dĕ̤ng-ngṳ̄' },
  { countryValue: 'cdo-hant', name: '閩東語（傳統漢字）' },
  { countryValue: 'cdo-latn', name: 'Mìng-dĕ̤ng-ngṳ̄ (Bàng-uâ-cê)' },
  { countryValue: 'ce', name: 'нохчийн' },
  { countryValue: 'ceb', name: 'Cebuano' },
  { countryValue: 'ch', name: 'Chamoru' },
  { countryValue: 'chn', name: 'chinuk wawa' },
  { countryValue: 'chr', name: 'ᏣᎳᎩ' },
  { countryValue: 'chy', name: 'Tsetsêhestâhese' },
  { countryValue: 'ckb', name: 'کوردی' },
  { countryValue: 'co', name: 'corsu' },
  { countryValue: 'cop', name: 'ϯⲙⲉⲧⲣⲉⲙⲛ̀ⲭⲏⲙⲓ' },
  { countryValue: 'cps', name: 'Capiceño' },
  { countryValue: 'cpx', name: '莆仙語 / Pó-sing-gṳ̂' },
  { countryValue: 'cpx-hans', name: '莆仙语（简体）' },
  { countryValue: 'cpx-hant', name: '莆仙語（繁體）' },
  { countryValue: 'cr', name: 'Nēhiyawēwin / ᓀᐦᐃᔭᐍᐏᐣ' },
  { countryValue: 'crh', name: 'qırımtatarca' },
  { countryValue: 'crh-cyrl', name: 'къырымтатарджа (Кирилл)' },
  { countryValue: 'crh-latn', name: 'qırımtatarca (Latin)' },
  { countryValue: 'crh-ro', name: 'tatarşa' },
  { countryValue: 'cs', name: 'čeština' },
  { countryValue: 'csb', name: 'kaszëbsczi' },
  { countryValue: 'cu', name: 'словѣньскъ / ⰔⰎⰑⰂⰡⰐⰠⰔⰍⰟ' },
  { countryValue: 'cv', name: 'чӑвашла' },
  { countryValue: 'cy', name: 'Cymraeg' },
  { countryValue: 'da', name: 'dansk' },
  { countryValue: 'dag', name: 'dagbanli' },
  { countryValue: 'de', name: 'Deutsch' },
  { countryValue: 'de-at', name: 'Österreichisches Deutsch' },
  { countryValue: 'de-ch', name: 'Schweizer Hochdeutsch' },
  { countryValue: 'de-formal', name: 'Deutsch (Sie-Form)' },
  { countryValue: 'dga', name: 'Dagaare' },
  { countryValue: 'din', name: 'Thuɔŋjäŋ' },
  { countryValue: 'diq', name: 'Zazaki' },
  { countryValue: 'dlg', name: 'долган тыла' },
  { countryValue: 'dsb', name: 'dolnoserbski' },
  { countryValue: 'dtp', name: 'Kadazandusun' },
  { countryValue: 'dty', name: 'डोटेली' },
  { countryValue: 'dua', name: 'Duálá' },
  { countryValue: 'dv', name: 'ދިވެހިބަސް' },
  { countryValue: 'dz', name: 'ཇོང་ཁ' },
  { countryValue: 'ee', name: 'eʋegbe' },
  { countryValue: 'efi', name: 'Efịk' },
  { countryValue: 'egl', name: 'Emiliàn' },
  { countryValue: 'el', name: 'Ελληνικά' },
  { countryValue: 'eml', name: 'emiliàn e rumagnòl' },
  { countryValue: 'en', name: 'English' },
  { countryValue: 'en-ca', name: 'Canadian English' },
  { countryValue: 'en-gb', name: 'British English' },
  { countryValue: 'eo', name: 'Esperanto' },
  { countryValue: 'es', name: 'español' },
  { countryValue: 'es-formal', name: 'español (formal)' },
  { countryValue: 'et', name: 'eesti' },
  { countryValue: 'eu', name: 'euskara' },
  { countryValue: 'ext', name: 'estremeñu' },
  { countryValue: 'fa', name: 'فارسی' },
  { countryValue: 'fat', name: 'mfantse' },
  { countryValue: 'ff', name: 'Fulfulde' },
  { countryValue: 'fi', name: 'suomi' },
  { countryValue: 'fit', name: 'meänkieli' },
  { countryValue: 'fj', name: 'Na Vosa Vakaviti' },
  { countryValue: 'fo', name: 'føroyskt' },
  { countryValue: 'fon', name: 'fɔ̀ngbè' },
  { countryValue: 'fr', name: 'français' },
  { countryValue: 'frc', name: 'français cadien' },
  { countryValue: 'frp', name: 'arpetan' },
  { countryValue: 'frr', name: 'Nordfriisk' },
  { countryValue: 'fur', name: 'furlan' },
  { countryValue: 'fvr', name: 'poor’íŋ belé’ŋ' },
  { countryValue: 'fy', name: 'Frysk' },
  { countryValue: 'ga', name: 'Gaeilge' },
  { countryValue: 'gaa', name: 'Ga' },
  { countryValue: 'gag', name: 'Gagauz' },
  { countryValue: 'gan', name: '贛語' },
  { countryValue: 'gan-hans', name: '赣语（简体）' },
  { countryValue: 'gan-hant', name: '贛語（繁體）' },
  { countryValue: 'gcf', name: 'kréyòl Gwadloup' },
  { countryValue: 'gcr', name: 'kriyòl gwiyannen' },
  { countryValue: 'gd', name: 'Gàidhlig' },
  { countryValue: 'gl', name: 'galego' },
  { countryValue: 'gld', name: 'на̄ни' },
  { countryValue: 'glk', name: 'گیلکی' },
  { countryValue: 'gn', name: "Avañe'ẽ" },
  { countryValue: 'gom', name: 'गोंयची कोंकणी / Gõychi Konknni' },
  { countryValue: 'gom-deva', name: 'गोंयची कोंकणी' },
  { countryValue: 'gom-latn', name: 'Gõychi Konknni' },
  { countryValue: 'gor', name: 'Bahasa Hulontalo' },
  { countryValue: 'got', name: '𐌲𐌿𐍄𐌹𐍃𐌺' },
  { countryValue: 'gpe', name: 'Ghanaian Pidgin' },
  { countryValue: 'grc', name: 'Ἀρχαία ἑλληνικὴ' },
  { countryValue: 'gsw', name: 'Alemannisch' },
  { countryValue: 'gu', name: 'ગુજરાતી' },
  { countryValue: 'guc', name: 'wayuunaiki' },
  { countryValue: 'gur', name: 'farefare' },
  { countryValue: 'guw', name: 'gungbe' },
  { countryValue: 'gv', name: 'Gaelg' },
  { countryValue: 'ha', name: 'Hausa' },
  { countryValue: 'hak', name: '客家語 / Hak-kâ-ngî' },
  { countryValue: 'hak-hans', name: '客家语（简体）' },
  { countryValue: 'hak-hant', name: '客家語（繁體）' },
  { countryValue: 'hak-latn', name: 'Hak-kâ-ngî (Pha̍k-fa-sṳ)' },
  { countryValue: 'haw', name: 'Hawaiʻi' },
  { countryValue: 'he', name: 'עברית' },
  { countryValue: 'hi', name: 'हिन्दी' },
  { countryValue: 'hif', name: 'Fiji Hindi' },
  { countryValue: 'hif-latn', name: 'Fiji Hindi' },
  { countryValue: 'hil', name: 'Ilonggo' },
  { countryValue: 'hke', name: 'kihunde' },
  { countryValue: 'hno', name: 'ہندکو' },
  { countryValue: 'hoc-latn', name: 'Ho' },
  { countryValue: 'hr', name: 'hrvatski' },
  { countryValue: 'hrx', name: 'Hunsrik' },
  { countryValue: 'hsb', name: 'hornjoserbsce' },
  { countryValue: 'hsn', name: '湘語' },
  { countryValue: 'ht', name: 'Kreyòl ayisyen' },
  { countryValue: 'hu', name: 'magyar' },
  { countryValue: 'hu-formal', name: 'magyar (formal)' },
  { countryValue: 'hy', name: 'հայերեն' },
  { countryValue: 'hyw', name: 'Արեւմտահայերէն' },
  { countryValue: 'ia', name: 'interlingua' },
  { countryValue: 'iba', name: 'Jaku Iban' },
  { countryValue: 'ibb', name: 'ibibio' },
  { countryValue: 'id', name: 'Bahasa Indonesia' },
  { countryValue: 'ie', name: 'Interlingue' },
  { countryValue: 'ig', name: 'Igbo' },
  { countryValue: 'igl', name: 'Igala' },
  { countryValue: 'ii', name: 'ꆇꉙ' },
  { countryValue: 'ik', name: 'Iñupiatun' },
  { countryValue: 'ike-cans', name: 'ᐃᓄᒃᑎᑐᑦ' },
  { countryValue: 'ike-latn', name: 'inuktitut' },
  { countryValue: 'ilo', name: 'Ilokano' },
  { countryValue: 'inh', name: 'гӀалгӀай' },
  { countryValue: 'io', name: 'Ido' },
  { countryValue: 'is', name: 'íslenska' },
  { countryValue: 'isv-cyrl', name: 'меджусловјанскы' },
  { countryValue: 'isv-latn', name: 'medžuslovjansky' }, // Not found
  { countryValue: 'it', name: 'italiano' },
  { countryValue: 'iu', name: 'ᐃᓄᒃᑎᑐᑦ / inuktitut' },
  { countryValue: 'ja', name: '日本語' },
  { countryValue: 'jam', name: 'Patois' },
  { countryValue: 'jbo', name: 'la .lojban.' },
  { countryValue: 'jut', name: 'jysk' },
  { countryValue: 'jv', name: 'Jawa' },
  { countryValue: 'jv-java', name: 'ꦗꦮ' },
  { countryValue: 'ka', name: 'ქართული' },
  { countryValue: 'kaa', name: 'Qaraqalpaqsha' },
  { countryValue: 'kab', name: 'Taqbaylit' },
  { countryValue: 'kai', name: 'Karai-karai' },
  { countryValue: 'kaj', name: 'Jju' },
  { countryValue: 'kbd', name: 'адыгэбзэ' },
  { countryValue: 'kbd-cyrl', name: 'адыгэбзэ' },
  { countryValue: 'kbp', name: 'Kabɩyɛ' },
  { countryValue: 'kcg', name: 'Tyap' },
  { countryValue: 'kea', name: 'kabuverdianu' },
  { countryValue: 'kg', name: 'Kongo' },
  { countryValue: 'kge', name: 'Kumoring' },
  { countryValue: 'khw', name: 'کھوار' },
  { countryValue: 'ki', name: 'Gĩkũyũ' },
  { countryValue: 'kiu', name: 'Kırmancki' },
  { countryValue: 'kjh', name: 'хакас' },
  { countryValue: 'kjp', name: 'ဖၠုံလိက်' },
  { countryValue: 'kk', name: 'қазақша' },
  { countryValue: 'kk-arab', name: 'قازاقشا (تٴوتە)' },
  { countryValue: 'kk-cn', name: 'قازاقشا (جۇنگو)' },
  { countryValue: 'kk-cyrl', name: 'қазақша (кирил)' },
  { countryValue: 'kk-kz', name: 'қазақша (Қазақстан)' },
  { countryValue: 'kk-latn', name: 'qazaqşa (latın)' },
  { countryValue: 'kk-tr', name: 'qazaqşa (Türkïya)' },
  { countryValue: 'kl', name: 'kalaallisut' },
  { countryValue: 'km', name: 'ភាសាខ្មែរ' },
  { countryValue: 'kn', name: 'ಕನ್ನಡ' },
  { countryValue: 'knc', name: 'Yerwa Kanuri' },
  { countryValue: 'ko', name: '한국어' },
  { countryValue: 'ko-kp', name: '조선말' },
  { countryValue: 'koi', name: 'перем коми' },
  { countryValue: 'kr', name: 'kanuri' },
  { countryValue: 'krc', name: 'къарачай-малкъар' },
  { countryValue: 'kri', name: 'Krio' },
  { countryValue: 'krj', name: 'Kinaray-a' },
  { countryValue: 'krl', name: 'karjal' },
  { countryValue: 'ks', name: 'کٲشُر' },
  { countryValue: 'ks-arab', name: 'کٲشُر' },
  { countryValue: 'ks-deva', name: 'कॉशुर' },
  { countryValue: 'ksh', name: 'Ripoarisch' },
  { countryValue: 'ksw', name: 'စှီၤ' },
  { countryValue: 'ku', name: 'kurdî' },
  { countryValue: 'ku-arab', name: 'کوردی (عەرەبی)' },
  { countryValue: 'ku-latn', name: 'kurdî (latînî)' },
  { countryValue: 'kum', name: 'къумукъ' },
  { countryValue: 'kus', name: 'Kʋsaal' },
  { countryValue: 'kv', name: 'коми' },
  { countryValue: 'kw', name: 'kernowek' },
  { countryValue: 'ky', name: 'кыргызча' },
  { countryValue: 'la', name: 'Latina' },
  { countryValue: 'lad', name: 'Ladino' },
  { countryValue: 'lb', name: 'Lëtzebuergesch' },
  { countryValue: 'lbe', name: 'лакку' },
  { countryValue: 'lez', name: 'лезги' },
  { countryValue: 'lfn', name: 'Lingua Franca Nova' },
  { countryValue: 'lg', name: 'Luganda' },
  { countryValue: 'li', name: 'Limburgs' },
  { countryValue: 'lij', name: 'Ligure' },
  { countryValue: 'liv', name: 'Līvõ kēļ' },
  { countryValue: 'ljp', name: 'Lampung Api' },
  { countryValue: 'lki', name: 'لەکی' },
  { countryValue: 'lld', name: 'Ladin' },
  { countryValue: 'lmo', name: 'lombard' },
  { countryValue: 'ln', name: 'lingála' },
  { countryValue: 'lo', name: 'ລາວ' },
  { countryValue: 'loz', name: 'Silozi' },
  { countryValue: 'lrc', name: 'لۊری شومالی' },
  { countryValue: 'lt', name: 'lietuvių' },
  { countryValue: 'ltg', name: 'latgaļu' },
  { countryValue: 'lua', name: 'ciluba' },
  { countryValue: 'lus', name: 'Mizo ţawng' },
  { countryValue: 'luz', name: 'لئری دوٙمینی' },
  { countryValue: 'lv', name: 'latviešu' },
  { countryValue: 'lzh', name: '文言' },
  { countryValue: 'lzz', name: 'Lazuri' },
  { countryValue: 'mad', name: 'Madhurâ' },
  { countryValue: 'mag', name: 'मगही' },
  { countryValue: 'mai', name: 'मैथिली' },
  { countryValue: 'map-bms', name: 'Basa Banyumasan' },
  { countryValue: 'mdf', name: 'мокшень' },
  { countryValue: 'mg', name: 'Malagasy' },
  { countryValue: 'mhr', name: 'олык марий' },
  { countryValue: 'mi', name: 'Māori' },
  { countryValue: 'min', name: 'Minangkabau' },
  { countryValue: 'mk', name: 'македонски' },
  { countryValue: 'ml', name: 'മലയാളം' },
  { countryValue: 'mn', name: 'монгол' },
  { countryValue: 'mnc', name: 'manju gisun' },
  { countryValue: 'mnc-latn', name: 'manju gisun' },
  { countryValue: 'mnc-mong', name: 'ᠮᠠᠨᠵᡠ ᡤᡳᠰᡠᠨ' },
  { countryValue: 'mni', name: 'ꯃꯤꯇꯩ ꯂꯣꯟ' },
  { countryValue: 'mnw', name: 'ဘာသာမန်' },
  { countryValue: 'mo', name: 'молдовеняскэ' },
  { countryValue: 'mos', name: 'moore' },
  { countryValue: 'mr', name: 'मराठी' },
  { countryValue: 'mrh', name: 'Mara' },
  { countryValue: 'mrj', name: 'кырык мары' },
  { countryValue: 'ms', name: 'Bahasa Melayu' },
  { countryValue: 'ms-arab', name: 'بهاس ملايو' },
  { countryValue: 'mt', name: 'Malti' },
  { countryValue: 'mui', name: 'Baso Palembang' },
  { countryValue: 'mwl', name: 'Mirandés' },
  { countryValue: 'my', name: 'မြန်မာဘာသာ' },
  { countryValue: 'myv', name: 'эрзянь' },
  { countryValue: 'mzn', name: 'مازِرونی' },
  { countryValue: 'nah', name: 'Nāhuatl' },
  { countryValue: 'nan', name: '閩南語 / Bân-lâm-gí' },
  { countryValue: 'nan-hant', name: '閩南語（傳統漢字）' },
  { countryValue: 'nan-latn-pehoeji', name: 'Bân-lâm-gí (Pe̍h-ōe-jī)' },
  { countryValue: 'nan-latn-tailo', name: 'Bân-lâm-gí (Tâi-lô)' },
  { countryValue: 'nap', name: 'Napulitano' },
  { countryValue: 'nb', name: 'norsk bokmål' },
  { countryValue: 'nds', name: 'Plattdüütsch' },
  { countryValue: 'nds-nl', name: 'Nedersaksies' },
  { countryValue: 'ne', name: 'नेपाली' },
  { countryValue: 'new', name: 'नेपाल भाषा' },
  { countryValue: 'nia', name: 'Li Niha' },
  { countryValue: 'nit', name: 'కొలామి' },
  { countryValue: 'niu', name: 'Niuē' },
  { countryValue: 'nl', name: 'Nederlands' },
  { countryValue: 'nl-informal', name: 'Nederlands (informeel)' },
  { countryValue: 'nmz', name: 'nawdm' },
  { countryValue: 'nn', name: 'norsk nynorsk' },
  { countryValue: 'no', name: 'norsk' },
  { countryValue: 'nod', name: 'ᨣᩤᩴᨾᩮᩬᩥᨦ' },
  { countryValue: 'nog', name: 'ногайша' },
  { countryValue: 'nov', name: 'Novial' },
  { countryValue: 'nqo', name: 'ߒߞߏ' },
  { countryValue: 'nr', name: 'isiNdebele seSewula' },
  { countryValue: 'nrm', name: 'Nouormand' }, // Not found
  { countryValue: 'nso', name: 'Sesotho sa Leboa' },
  { countryValue: 'nup', name: 'Nupe' },
  { countryValue: 'nv', name: 'Diné bizaad' },
  { countryValue: 'ny', name: 'Chi-Chewa' },
  { countryValue: 'nyn', name: 'runyankore' },
  { countryValue: 'nyo', name: 'Orunyoro' },
  { countryValue: 'nys', name: 'Nyunga' },
  { countryValue: 'oc', name: 'occitan' },
  { countryValue: 'ojb', name: 'Ojibwemowin' },
  { countryValue: 'olo', name: 'livvinkarjala' },
  { countryValue: 'om', name: 'Oromoo' },
  { countryValue: 'or', name: 'ଓଡ଼ିଆ' },
  { countryValue: 'os', name: 'ирон' },
  { countryValue: 'pa', name: 'ਪੰਜਾਬੀ' },
  { countryValue: 'pag', name: 'Pangasinan' },
  { countryValue: 'pam', name: 'Kapampangan' },
  { countryValue: 'pap', name: 'Papiamentu' },
  { countryValue: 'pap-aw', name: 'Papiamento (Aruba)' },
  { countryValue: 'pcd', name: 'Picard' },
  { countryValue: 'pcm', name: 'Naijá' },
  { countryValue: 'pdc', name: 'Deitsch' },
  { countryValue: 'pdt', name: 'Plautdietsch' },
  { countryValue: 'pfl', name: 'Pälzisch' },
  { countryValue: 'pi', name: 'पालि' },
  { countryValue: 'pih', name: 'Norfuk / Pitkern' },
  { countryValue: 'pl', name: 'polski' },
  { countryValue: 'pms', name: 'Piemontèis' },
  { countryValue: 'pnb', name: 'پنجابی' },
  { countryValue: 'pnt', name: 'Ποντιακά' },
  { countryValue: 'ppl', name: 'Nawat' },
  { countryValue: 'prg', name: 'prūsiskan' },
  { countryValue: 'ps', name: 'پښتو' },
  { countryValue: 'pt', name: 'português' },
  { countryValue: 'pt-br', name: 'português do Brasil' },
  { countryValue: 'pwn', name: 'pinayuanan' },
  { countryValue: 'qu', name: 'Runa Simi' },
  { countryValue: 'qug', name: 'Runa shimi' },
  { countryValue: 'rgn', name: 'Rumagnôl' },
  { countryValue: 'rif', name: 'Tarifit' },
  { countryValue: 'rki', name: 'ရခိုင်' },
  { countryValue: 'rm', name: 'rumantsch' },
  { countryValue: 'rmc', name: 'romaňi čhib' },
  { countryValue: 'rmy', name: 'romani čhib' },
  { countryValue: 'rn', name: 'ikirundi' },
  { countryValue: 'ro', name: 'română' },
  { countryValue: 'roa-tara', name: 'tarandíne' },
  { countryValue: 'rsk', name: 'руски' },
  { countryValue: 'ru', name: 'русский' },
  { countryValue: 'rue', name: 'русиньскый' },
  { countryValue: 'rup', name: 'armãneashti' },
  { countryValue: 'ruq', name: 'Vlăheşte' },
  { countryValue: 'ruq-cyrl', name: 'Влахесте' },
  { countryValue: 'ruq-latn', name: 'Vlăheşte' },
  { countryValue: 'rut', name: 'мыхаӀбишды' },
  { countryValue: 'rw', name: 'Ikinyarwanda' },
  { countryValue: 'ryu', name: 'うちなーぐち' },
  { countryValue: 'sa', name: 'संस्कृतम्' },
  { countryValue: 'sah', name: 'саха тыла' },
  { countryValue: 'sas', name: 'Sasak' },
  { countryValue: 'sat', name: 'ᱥᱟᱱᱛᱟᱲᱤ' },
  { countryValue: 'sc', name: 'sardu' },
  { countryValue: 'scn', name: 'sicilianu' },
  { countryValue: 'sco', name: 'Scots' },
  { countryValue: 'sd', name: 'سنڌي' },
  { countryValue: 'sdc', name: 'Sassaresu' },
  { countryValue: 'sdh', name: 'کوردی خوارگ' },
  { countryValue: 'se', name: 'davvisámegiella' },
  { countryValue: 'se-fi', name: 'davvisámegiella (Suoma bealde)' },
  { countryValue: 'se-no', name: 'davvisámegiella (Norgga bealde)' },
  { countryValue: 'se-se', name: 'davvisámegiella (Ruoŧa bealde)' },
  { countryValue: 'sei', name: 'Cmique Itom' },
  { countryValue: 'ses', name: 'Koyraboro Senni' },
  { countryValue: 'sg', name: 'Sängö' },
  { countryValue: 'sgs', name: 'žemaitėška' },
  { countryValue: 'sh', name: 'srpskohrvatski / српскохрватски' },
  { countryValue: 'sh-cyrl', name: 'српскохрватски (ћирилица)' },
  { countryValue: 'sh-latn', name: 'srpskohrvatski (latinica)' },
  { countryValue: 'shi', name: 'Taclḥit' },
  { countryValue: 'shn', name: 'တႆး' },
  { countryValue: 'shy', name: 'tacawit' },
  { countryValue: 'shy-latn', name: 'tacawit' },
  { countryValue: 'si', name: 'සිංහල' },
  { countryValue: 'sjd', name: 'кӣллт са̄мь кӣлл' },
  { countryValue: 'sje', name: 'bidumsámegiella' },
  { countryValue: 'sk', name: 'slovenčina' },
  { countryValue: 'skr', name: 'سرائیکی' },
  { countryValue: 'skr-arab', name: 'سرائیکی' },
  { countryValue: 'sl', name: 'slovenščina' },
  { countryValue: 'sli', name: 'Schläsch' },
  { countryValue: 'sm', name: 'Gagana Samoa' },
  { countryValue: 'sma', name: 'åarjelsaemien' },
  { countryValue: 'smn', name: 'anarâškielâ' },
  { countryValue: 'sms', name: 'nuõrttsääʹmǩiõll' },
  { countryValue: 'sn', name: 'chiShona' },
  { countryValue: 'so', name: 'Soomaaliga' },
  { countryValue: 'sq', name: 'shqip' },
  { countryValue: 'sr', name: 'српски / srpski' },
  { countryValue: 'sr-ec', name: 'српски (ћирилица)' },
  { countryValue: 'sr-el', name: 'srpski (latinica)' },
  { countryValue: 'srn', name: 'Sranantongo' },
  { countryValue: 'sro', name: 'sardu campidanesu' },
  { countryValue: 'ss', name: 'SiSwati' },
  { countryValue: 'st', name: 'Sesotho' },
  { countryValue: 'stq', name: 'Seeltersk' },
  { countryValue: 'sty', name: 'себертатар' },
  { countryValue: 'su', name: 'Sunda' },
  { countryValue: 'sv', name: 'svenska' },
  { countryValue: 'sw', name: 'Kiswahili' },
  { countryValue: 'syl', name: 'ꠍꠤꠟꠐꠤ' },
  { countryValue: 'szl', name: 'ślůnski' },
  { countryValue: 'szy', name: 'Sakizaya' },
  { countryValue: 'ta', name: 'தமிழ்' },
  { countryValue: 'tay', name: 'Tayal' },
  { countryValue: 'tcy', name: 'ತುಳು' },
  { countryValue: 'tdd', name: 'ᥖᥭᥰ ᥖᥬᥲ ᥑᥨᥒᥰ' },
  { countryValue: 'te', name: 'తెలుగు' },
  { countryValue: 'tet', name: 'tetun' },
  { countryValue: 'tg', name: 'тоҷикӣ' },
  { countryValue: 'tg-cyrl', name: 'тоҷикӣ' },
  { countryValue: 'tg-latn', name: 'tojikī' },
  { countryValue: 'th', name: 'ไทย' },
  { countryValue: 'ti', name: 'ትግርኛ' },
  { countryValue: 'tig', name: 'ትግሬ' },
  { countryValue: 'tk', name: 'Türkmençe' },
  { countryValue: 'tl', name: 'Tagalog' },
  { countryValue: 'tly', name: 'tolışi' },
  { countryValue: 'tn', name: 'Setswana' },
  { countryValue: 'to', name: 'lea faka-Tonga' },
  { countryValue: 'tok', name: 'toki pona' },
  { countryValue: 'tpi', name: 'Tok Pisin' },
  { countryValue: 'tr', name: 'Türkçe' },
  { countryValue: 'tru', name: 'Ṫuroyo' },
  { countryValue: 'trv', name: 'Seediq' },
  { countryValue: 'ts', name: 'Xitsonga' },
  { countryValue: 'tt', name: 'татарча / tatarça' },
  { countryValue: 'tt-cyrl', name: 'татарча' },
  { countryValue: 'tt-latn', name: 'tatarça' },
  { countryValue: 'ttj', name: 'Orutooro' },
  { countryValue: 'tum', name: 'chiTumbuka' },
  { countryValue: 'tw', name: 'Twi' },
  { countryValue: 'ty', name: 'reo tahiti' },
  { countryValue: 'tyv', name: 'тыва дыл' },
  { countryValue: 'tzm', name: 'ⵜⴰⵎⴰⵣⵉⵖⵜ' },
  { countryValue: 'udm', name: 'удмурт' },
  { countryValue: 'ug', name: 'ئۇيغۇرچە / Uyghurche' },
  { countryValue: 'ug-arab', name: 'ئۇيغۇرچە' },
  { countryValue: 'ug-latn', name: 'Uyghurche' },
  { countryValue: 'uk', name: 'українська' },
  { countryValue: 'ur', name: 'اردو' },
  { countryValue: 'uz', name: 'oʻzbekcha / ўзбекча' },
  { countryValue: 've', name: 'Tshivenda' },
  { countryValue: 'vec', name: 'vèneto' },
  { countryValue: 'vep', name: 'vepsän kel’' },
  { countryValue: 'vi', name: 'Tiếng Việt' },
  { countryValue: 'vls', name: 'West-Vlams' },
  { countryValue: 'vmf', name: 'Mainfränkisch' },
  { countryValue: 'vmw', name: 'emakhuwa' },
  { countryValue: 'vo', name: 'Volapük' },
  { countryValue: 'vot', name: 'Vaďďa' },
  { countryValue: 'vro', name: 'võro' },
  { countryValue: 'wa', name: 'walon' },
  { countryValue: 'wal', name: 'wolaytta' },
  { countryValue: 'war', name: 'Winaray' },
  { countryValue: 'wls', name: 'Fakaʻuvea' },
  { countryValue: 'wlx', name: 'waale' },
  { countryValue: 'wo', name: 'Wolof' },
  { countryValue: 'wuu', name: '吴语' },
  { countryValue: 'wuu-hans', name: '吴语（简体）' },
  { countryValue: 'wuu-hant', name: '吳語（正體）' },
  { countryValue: 'xal', name: 'хальмг' },
  { countryValue: 'xh', name: 'isiXhosa' },
  { countryValue: 'xmf', name: 'მარგალური' },
  { countryValue: 'xsy', name: 'saisiyat' },
  { countryValue: 'yi', name: 'ייִדיש' },
  { countryValue: 'yo', name: 'Yorùbá' },
  { countryValue: 'yrl', name: 'Nhẽẽgatú' },
  { countryValue: 'yua', name: 'maaya t’aan' },
  { countryValue: 'yue', name: '粵語' },
  { countryValue: 'yue-hans', name: '粵语（简体）' },
  { countryValue: 'yue-hant', name: '粵語（繁體）' },
  { countryValue: 'za', name: 'Vahcuengh' },
  { countryValue: 'zea', name: 'Zeêuws' },
  { countryValue: 'zgh', name: 'ⵜⴰⵎⴰⵣⵉⵖⵜ ⵜⴰⵏⴰⵡⴰⵢⵜ' },
  { countryValue: 'zh', name: '中文' },
  { countryValue: 'zh-cn', name: '中文（中国大陆）' },
  { countryValue: 'zh-hans', name: '中文（简体）' },
  { countryValue: 'zh-hant', name: '中文（繁體）' },
  { countryValue: 'zh-hk', name: '中文（香港）' },
  { countryValue: 'zh-mo', name: '中文（澳門）' },
  { countryValue: 'zh-my', name: '中文（马来西亚）' },
  { countryValue: 'zh-sg', name: '中文（新加坡）' },
  { countryValue: 'zh-tw', name: '中文（臺灣）' },
  { countryValue: 'zu', name: 'isiZulu' },
] as const;
